name: Build Test Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the code 
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Start backend
      run: npm run start:be &
    - name: Start forntend
      run: npm run start-fe &
    - name: Install Playwright browsers
      run: npx playwright install 
    - name: Execute UI tests
      run: npm run test 

  
